spring:
  application:
    name: eventmesh-ai

  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: INFO

app:
  kafka:
    topic:
      raw-events: raw-events-topic
      dlq: dlq-topic